/**
 * Centralized error codes for structured error responses.
 * These codes are used across all microservices and mapped to HTTP status codes in the API Gateway.
 */
export const ERROR_CODES = {
  // Generic errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // User errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',

  // Auth errors
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  OAUTH_PROVIDER_MISMATCH: 'OAUTH_PROVIDER_MISMATCH',
  GOOGLE_TOKEN_INVALID: 'GOOGLE_TOKEN_INVALID',
  GOOGLE_EMAIL_NOT_VERIFIED: 'GOOGLE_EMAIL_NOT_VERIFIED',
  APPLE_TOKEN_INVALID: 'APPLE_TOKEN_INVALID',
  PASSWORD_TOO_WEAK: 'PASSWORD_TOO_WEAK',
  PASSWORD_RESET_TOKEN_INVALID: 'PASSWORD_RESET_TOKEN_INVALID',
  PASSWORD_RESET_TOKEN_EXPIRED: 'PASSWORD_RESET_TOKEN_EXPIRED',
  CURRENT_PASSWORD_INCORRECT: 'CURRENT_PASSWORD_INCORRECT',
  PASSWORD_CHANGE_NOT_AVAILABLE: 'PASSWORD_CHANGE_NOT_AVAILABLE',

  // Payment errors
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_COMPLETED: 'PAYMENT_ALREADY_COMPLETED',
  PAYMENT_ALREADY_REFUNDED: 'PAYMENT_ALREADY_REFUNDED',
  REFUND_NOT_ALLOWED: 'REFUND_NOT_ALLOWED',
  REFUND_AMOUNT_EXCEEDS_PAYMENT: 'REFUND_AMOUNT_EXCEEDS_PAYMENT',
  PAYMENT_PROCESSING_FAILED: 'PAYMENT_PROCESSING_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * Structured error payload for RPC exceptions.
 * This is serialized to JSON and passed through RpcException.
 */
export interface StructuredError {
  code: ErrorCode;
  message: string;
  field?: string;
  details?: Record<string, unknown>;
}

/**
 * Maps error codes to their corresponding HTTP status codes.
 * Used by the API Gateway's global exception filter.
 */
export const ERROR_CODE_TO_HTTP_STATUS: Record<ErrorCode, number> = {
  // Generic errors
  [ERROR_CODES.INTERNAL_ERROR]: 500,
  [ERROR_CODES.VALIDATION_ERROR]: 400,
  [ERROR_CODES.NOT_FOUND]: 404,
  [ERROR_CODES.UNAUTHORIZED]: 401,
  [ERROR_CODES.FORBIDDEN]: 403,

  // User errors
  [ERROR_CODES.USER_NOT_FOUND]: 404,
  [ERROR_CODES.USER_ALREADY_EXISTS]: 409,
  [ERROR_CODES.EMAIL_ALREADY_IN_USE]: 409,

  // Auth errors
  [ERROR_CODES.INVALID_CREDENTIALS]: 401,
  [ERROR_CODES.INVALID_TOKEN]: 401,
  [ERROR_CODES.TOKEN_EXPIRED]: 401,
  [ERROR_CODES.REFRESH_TOKEN_INVALID]: 401,
  [ERROR_CODES.REFRESH_TOKEN_EXPIRED]: 401,
  [ERROR_CODES.OAUTH_PROVIDER_MISMATCH]: 409,
  [ERROR_CODES.GOOGLE_TOKEN_INVALID]: 401,
  [ERROR_CODES.GOOGLE_EMAIL_NOT_VERIFIED]: 400,
  [ERROR_CODES.APPLE_TOKEN_INVALID]: 401,
  [ERROR_CODES.PASSWORD_TOO_WEAK]: 400,
  [ERROR_CODES.PASSWORD_RESET_TOKEN_INVALID]: 400,
  [ERROR_CODES.PASSWORD_RESET_TOKEN_EXPIRED]: 400,
  [ERROR_CODES.CURRENT_PASSWORD_INCORRECT]: 400,
  [ERROR_CODES.PASSWORD_CHANGE_NOT_AVAILABLE]: 400,

  // Payment errors
  [ERROR_CODES.PAYMENT_NOT_FOUND]: 404,
  [ERROR_CODES.PAYMENT_ALREADY_COMPLETED]: 400,
  [ERROR_CODES.PAYMENT_ALREADY_REFUNDED]: 400,
  [ERROR_CODES.REFUND_NOT_ALLOWED]: 400,
  [ERROR_CODES.REFUND_AMOUNT_EXCEEDS_PAYMENT]: 400,
  [ERROR_CODES.PAYMENT_PROCESSING_FAILED]: 500,
};

/**
 * Helper function to create a structured error object.
 */
export function createStructuredError(
  code: ErrorCode,
  message: string,
  field?: string,
  details?: Record<string, unknown>,
): StructuredError {
  return { code, message, field, details };
}
